// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "forge-std/Test.sol";
import "../src/OrdoReceiptLog.sol";
import "../src/OrdoSettlement.sol";

contract OrdoReceiptLogTest is Test {
    OrdoSettlement settlement;
    OrdoReceiptLog receiptLog;

    address auctioneer = makeAddr("auctioneer");
    address treasury = makeAddr("treasury");
    address rando = makeAddr("rando");

    // Fixtures generated by packages/core/src/receipt.ts (merkleRoot /
    // merkleProof over leaves 0x01..0x05). If either implementation changes
    // shape, these stop matching — which is the point of pinning them.
    bytes32 constant ROOT = 0x3856185f708a95a4cef51f6538ed3ea849702a46e020430070ac99c94a831c58;

    function setUp() public {
        settlement = new OrdoSettlement(auctioneer, treasury, 500, 500);
        receiptLog = new OrdoReceiptLog(address(settlement));
    }

    function leaf(uint256 i) internal pure returns (bytes32) {
        return bytes32(i);
    }

    function test_OnlyAuctioneerCommits() public {
        vm.prank(rando);
        vm.expectRevert(OrdoReceiptLog.NotAuctioneer.selector);
        receiptLog.commit(ROOT, 5);

        vm.prank(auctioneer);
        receiptLog.commit(ROOT, 5);
        assertEq(receiptLog.total(), 1);
    }

    function test_RotatingAuctioneerOnSettlementRotatesHereToo() public {
        address next = makeAddr("next-auctioneer");
        settlement.setAuctioneer(next); // test contract deployed it, so it is owner

        vm.prank(auctioneer);
        vm.expectRevert(OrdoReceiptLog.NotAuctioneer.selector);
        receiptLog.commit(ROOT, 5);

        vm.prank(next);
        receiptLog.commit(ROOT, 5);
        assertEq(receiptLog.total(), 1);
    }

    function test_RevertWhen_LogShrinks() public {
        vm.startPrank(auctioneer);
        receiptLog.commit(ROOT, 5);
        vm.expectRevert(abi.encodeWithSelector(OrdoReceiptLog.ShrinkingLog.selector, 5, 4));
        receiptLog.commit(ROOT, 4);
        vm.stopPrank();
    }

    function test_RevertWhen_RootEmpty() public {
        vm.prank(auctioneer);
        vm.expectRevert(OrdoReceiptLog.EmptyRoot.selector);
        receiptLog.commit(bytes32(0), 1);
    }

    function test_VerifyMatchesTypescriptFixtures() public {
        vm.prank(auctioneer);
        receiptLog.commit(ROOT, 5);

        // proof[0]
        bytes32[] memory p0 = new bytes32[](3);
        p0[0] = bytes32(uint256(2));
        p0[1] = 0x2e174c10e159ea99b867ce3205125c24a42d128804e4070ed6fcc8cc98166aa0;
        p0[2] = bytes32(uint256(5));
        assertTrue(receiptLog.verify(leaf(1), p0, 0), "leaf 1");

        // proof[3]
        bytes32[] memory p3 = new bytes32[](3);
        p3[0] = bytes32(uint256(3));
        p3[1] = 0xe90b7bceb6e7df5418fb78d8ee546e97c83a08bbccc01a0644d599ccd2a7c2e0;
        p3[2] = bytes32(uint256(5));
        assertTrue(receiptLog.verify(leaf(4), p3, 0), "leaf 4");

        // proof[4] — the odd leaf that carries up unpaired.
        bytes32[] memory p4 = new bytes32[](1);
        p4[0] = 0x0c48ddc2b8d6d066c52fc608d4d0254f418bea6cd8424fe95390ac87323f9c9f;
        assertTrue(receiptLog.verify(leaf(5), p4, 0), "leaf 5");

        // A leaf that was never in the tree fails against every proof.
        assertFalse(receiptLog.verify(leaf(9), p0, 0), "forged leaf");
        // The right leaf with the wrong proof fails too.
        assertFalse(receiptLog.verify(leaf(1), p4, 0), "wrong proof");
    }

    function test_LatestReflectsMostRecentCommit() public {
        vm.startPrank(auctioneer);
        receiptLog.commit(ROOT, 5);
        bytes32 nextRoot = keccak256("next");
        receiptLog.commit(nextRoot, 12);
        vm.stopPrank();

        OrdoReceiptLog.Commitment memory c = receiptLog.latest();
        assertEq(c.root, nextRoot);
        assertEq(c.count, 12);
        assertEq(receiptLog.total(), 2);
    }
}
